name: 'Detect Build Mode'
description: 'Detects build mode from git ref'

outputs:
  mode:
    description: 'Build mode (release, prerelease, snapshot)'
    value: ${{ steps.set_mode.outputs.mode }}
  branch_type:
    description: 'Branch type (release, prerelease, main, feature)'
    value: ${{ steps.set_mode.outputs.branch_type }}

runs:
  using: composite
  steps:
    - id: set_mode
      shell: bash
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          if [[ $GITHUB_REF == *"-pre"* || $GITHUB_REF == *"-rc"* ]]; then
            echo "mode=prerelease" >> $GITHUB_OUTPUT
            echo "branch_type=prerelease" >> $GITHUB_OUTPUT
          else
            echo "mode=release" >> $GITHUB_OUTPUT
            echo "branch_type=release" >> $GITHUB_OUTPUT
          fi
        elif [[ $GITHUB_REF == refs/heads/main ]]; then
          echo "mode=snapshot" >> $GITHUB_OUTPUT
          echo "branch_type=main" >> $GITHUB_OUTPUT
        else
          echo "mode=snapshot" >> $GITHUB_OUTPUT
          echo "branch_type=feature" >> $GITHUB_OUTPUT
        fi 