aws:
  family:
    name: "upbound-provider-aws"
    package: "xpkg.upbound.io/upbound/provider-family-aws"
    version: "v1"
  services:
    - name: "provider-aws-iam"
      package: "xpkg.upbound.io/upbound/provider-aws-iam"
      version: "v1"
    - name: "provider-aws-s3"
      package: "xpkg.upbound.io/upbound/provider-aws-s3"
      version: "v1"
    - name: "provider-aws-rds"
      package: "xpkg.upbound.io/upbound/provider-aws-rds"
      version: "v1"
    - name: "provider-aws-lambda"
      package: "xpkg.upbound.io/upbound/provider-aws-lambda"
      version: "v1"
    - name: "provider-aws-sqs"
      package: "xpkg.upbound.io/upbound/provider-aws-sqs"
      version: "v1"
    - name: "provider-aws-sns"
      package: "xpkg.upbound.io/upbound/provider-aws-sns"
      version: "v1"
    - name: "provider-aws-cloudwatch"
      package: "xpkg.upbound.io/upbound/provider-aws-cloudwatch"
      version: "v1"
    - name: "provider-aws-cloudtrail"
      package: "xpkg.upbound.io/upbound/provider-aws-cloudtrail"
      version: "v1"

otherProviders:
  - name: "provider-helm"
    package: "xpkg.upbound.io/upbound/provider-helm"
    version: "v0.20.4"
  - name: "provider-kubernetes"
    package: "xpkg.upbound.io/upbound/provider-kubernetes"
    version: "v0.16.3" 