kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: crosslocal-cluster

# Configure node defaults
nodes:
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    - containerPort: 80
      hostPort: 8080
    - containerPort: 443
      hostPort: 8443
      protocol: TCP
  - role: worker
  - role: worker
  
# Enable feature gates
featureGates:
  # Add any feature gates you want to enable 


