name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'feature/**'
    tags:
      - 'v*'

env:
  GO_VERSION: '1.22.1'
  ARTIFACT_RETENTION_DAYS: 30

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_mode: ${{ steps.detect_mode.outputs.mode }}
      branch_type: ${{ steps.detect_mode.outputs.branch_type }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: ./.github/actions/detect-build-mode
        id: detect_mode

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build and test
        run: |
          go build ./...

  snapshot:
    needs: [setup, build]
    if: needs.setup.outputs.build_mode == 'snapshot'
    strategy:
      matrix:
        include:
          - branch_type: main
            artifact_name: crosslab-main-snapshot
          - branch_type: feature
            artifact_name: crosslab-feature-snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: goreleaser/goreleaser-action@v5
        with:
          args: release --snapshot --clean --skip=publish --output-dir dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prerelease:
    needs: [setup, build]
    if: needs.setup.outputs.build_mode == 'prerelease'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean --prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [setup, build]
    if: needs.setup.outputs.build_mode == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  artifacts:
    needs: [setup, snapshot]
    if: needs.setup.outputs.build_mode == 'snapshot'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.setup.outputs.branch_type == 'main' && 'crosslab-main-snapshot' || 'crosslab-feature-snapshot' }}
          path: dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.setup.outputs.branch_type == 'main' && 'crosslab-main-snapshot'  }}
          path: dist/*
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}

      